export const mainPage = { 
    // logo: '[data-e2e="components.layout.logoDesktopGrd"]', 
    // buttonAllDrugStores: '[data-e2e="layout.header.btnMapUkraine"]',
     inputSearch: 'input#searchInput:nth-of-type(1)', 
     buttonSearch: 'button.cp-form-group-search-btn-grd', 
     buttonAddress: '[data-e2e="layout.header.btnAddress"]', 
    // buttonChangeCity: '[class="cp-drawer-city__address-navigation"] [class*="cp-btn"]', 
     inputSearchCity: '[data-e2e="components.ui.searchInput"] input#searchInput',
     buttonSearchCity: '[data-e2e="components.ui.searchInput"] button.cp-form-group-search-btn', 
     firstCitySuggestion: '[class="cp-backlight"]', 
     headerWrapper: 'div.cp-header-mobile-grd__wrapper.cp-block', 
     searchResult: 'div[class="cp-search-text"]', 
    // topDrugsSection: '[data-e2e="components.reference.topReferences"]',
     firstResult: 'a[class="cp-drug-item__title"]:nth-of-type(1)', 
     firstResultPhoto: '[href="/dec/270555/66303/"]:nth-of-type(1)',
    // ruSwitcher: '[data-e2e="layout.themeSwitcher.ukrLight"]', 
    // uaSwitcher: '[data-e2e="layout.themeSwitcher.ukrDark"]', 
     buttonLogin: '[data-e2e="layout.header.btnLogin"]', 
    // buttonFavorites: '[data-e2e="layout.header.btnFavorites"]',
     buttonMedExpertProfile: '[class*="cp-auth__list-loginDoctor"]', 
    // buttonCategories: 'button#headerCategoryBtn', 
    // jumbotron: '[class="cp-jumbotron"]', 
    // topDrugPhoto: '[class*="top-reference-card"] [title="Алохол (Allocholum)"]:nth-of-type(1)', 
    // sectionCategories: '[data-e2e="components.home.categoriesCompendium"]', 
    // buttonAllNews: '[class="cp-keenslider__header-info"] [href="/uk/news/"]',
    // newsText: '.cp-blog-card-normal__info a[href*="rannya"]'
} 